---
title: 'Project 4: Baysian modeling of hurrican trajectories'
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(truncnorm)
library(maps)
library(matrixcalc)
library(dplyr)
library(data.table)
library(caret)
library(mvtnorm)
```

## Introduction

The 1989 Atlantic hurricane season officially began on June 1, 1989, and lasted until November 30, 1989. However storms can form outside these dates. For example, Tropical Storm Karen lasted until December 4. This season had average activity with 15 depressions, 3 became a tropical storm, 5 became a hurricane, and 2 became a major hurricane. This was a damaging season because this season featured the powerful Hurricane Hugo. Overall, the storms of the season collectively caused 136 fatalities and at least $10.2 billion in damage. Therefore, efforts to abtain deeper understanding of their physical mechanisms such as Wind.kt (Maximum wind speed in Knot at each check point) for the development and tracking is very important for us.


## Obejctive
Randomly select 80% hurricanes and design a MCMC algorithm to estiamte the posterior distributions of the model parameters. Estimate the model parameters using posteri means and construct their 95% credibility intervals. Apply the developped model to track the remaining 20% hurricans, and evaluate how well your model could predict and track these hurricanes.


## Data
hurrican356.csv collected the track data of 356 hurricanes in  the North Atlantic area since 1989. For all the storms, their location (longitude \& latitude) and maximum wind speed were recorded every 6 hours. The data includes the following variables

1. **ID**:  ID of the hurricans
2. **Season**: In which \textbf{year} the hurricane occurred 
3. **Month**: In which \textbf{month} the hurricane occurred 
4. **Nature**:  Nature of the hurricane 
  + ET: Extra Tropical
  + DS: Disturbance
  + NR: Not Rated
  + SS: Sub Tropical
  + TS: Tropical Storm
5. **time**: dates and time of the record  
6. **Latitude** and **Longitude**:  The location of  a hurricane check point 
7. **Wind.kt**  Maximum wind speed (in Knot) at each check point 

To make the model more interpretable, we delete the storms with the "Nature" being "Not Rated", and then randomly split the data into training data and test data.

## Method
Let $t$ be time (in hours) since a hurricane began, and For each hurrican $i$, we denote $\{ Y_{i,1}(t), Y_{i,2}(t), Y_{i,3}(t)\},j=1,2,3$ be the latitude, longitude, and wind speed at time $t$. The following Baysian model was suggested:
$$Y_{i}(t+6) =  \mu_{i}(t) +\rho Y_{i}(t) + \epsilon_{i}(t)$$

And then we have:

$$\mu_{i}(t) =  \beta_{0}+x_{i,1}(t)\beta_{1} +
x_{i,2} \beta_{2} + ]
x_{i,3}\beta_{3} +
\sum_{k=1}^3\beta_{3+k}\Delta_{i,k}(t-6)$$ 
$$\Delta_{i,k}(t-6) = Y_{i,k}(t) -Y_{i,k}(t-6),k=1,2,3$$
For
$\pi(\boldsymbol{\beta})$ ~ $MVN(\mathbf 0,\ diag(1, p))$, 

$\pi(\rho)$ follows a trucated normal  $N_{[0,1]}(0.5, 1/5)$ 

$\pi((\sigma^2)^{-1})$ follows a inverse-gamma $(0.001, 0.001)$

What we can conclude from these information: 

Yi is a linear combination of $\mu_i$ and $\rho Y_{i}(t)$  and $\epsilon_{i}(t)$. While $\mu_i$ and $\rho Y_{i}(t)$ is a constant. So $Y_{i}(t+6)$ follow normal distribution with $\mu_{new}(t)$ and variance $\sigma^2$:

$$Y_i(t+6)\sim Normal(\mu_{new}(t),\sigma^2)$$

$$\mu_{new}(t)=\mu_{i}(t)+\rho Y_{i}(t) $$
To exclude the time series influence on $Y_i$ we choose to use $$\epsilon_i=Y_i(t+6)-\mu_{new}\sim Normal(0,\sigma^2)$$

We set i is the ith hurricane, n is the total number of hurricane. The k denote the kth speed among this hurricane, m is the total measured speeds among this hurricane. 

The poesteria distribution 
$$f(\epsilon_i|\boldsymbol\beta,\rho,\sigma^2 )=\frac{1}{\sqrt{2\pi}\sigma}exp(-\frac{(Y_i(t+6)-\mu_{new}-0)^2}{2\sigma^2})$$
Poesterian distribution: $$\pi(\boldsymbol\beta,\rho,\sigma^2|\epsilon_i)\propto \prod_{i=1}^{n}\prod_{k=1}^{m}f(\epsilon_i|\boldsymbol\beta,\rho,\sigma^2 )*\pi(\boldsymbol{\beta})*\pi(\rho)*\pi((\sigma^2)^{-1})$$

Take the log form:
$$\pi'(\boldsymbol\beta,\rho,\sigma^2|\epsilon_i)\propto \sum_{i=1}^{n}\sum_{k=1}^{m}log(f(\epsilon_i|\boldsymbol\beta,\rho,\sigma^2 ))+log(\pi(\boldsymbol\beta))+log(\pi(\rho))+log(\pi((\sigma^2)^{-1}))$$

To find the poeteria distribution, we use the random walk in Metropolis-Hasting algorithm:
The probability of accepting :
$$\alpha(\lambda|\boldsymbol\theta)=min(1,\frac{\pi(\boldsymbol\lambda)q(\boldsymbol\theta|\boldsymbol\lambda)}{\pi(\boldsymbol\theta)q(\boldsymbol\lambda\boldsymbol\theta)})$$
In this situation, we have: $$q(\theta|\lambda)=q(\lambda|\theta)$$

So, $$\alpha(\lambda|\boldsymbol\theta)=min(1,\frac{\pi(\boldsymbol\lambda)}{\pi(\boldsymbol\theta)})=min(1,\pi'(\boldsymbol\lambda)-\pi'(\boldsymbol\theta))$$

Finally ,we can compare the $\alpha(\lambda|\boldsymbol\theta)$ with the random drawed uniform(0,1) number,if $\alpha(\lambda|\boldsymbol\theta)$ is larger, accept the $\lambda$, otherwise still accept $ \theta$.

## Result

The chain plots of parameters are shown below. Since the accept rate decrease after 1000 iterations, to make transition more efficient, the step size for random walk during first 1000 iterations is set to be different from the second half iterations. 

Almost every 





