---
title: "proj3"
author: "Zongchao Liu"
date: "4/20/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(numDeriv)
library(pracma)
```


# Import and clean data

```{r,message=FALSE}
data = read_csv("./covid19-1.csv") %>% janitor::clean_names()
#skimr::skim(data)

#看一眼国家的数据
names(data)
length(unique(data$country_region)) #169
data %>%
  group_by(country_region) %>%
  summarise(n_cases = max(confirmed_cases)) %>% #confirmed_cases = 累计cases
  filter(n_cases != 0) %>%
  arrange(desc(n_cases)) %>% #nrow(.) = 145
  .[1:10,] %>%
  ggplot(aes(x = reorder(country_region,-n_cases), y = log(n_cases),fill = country_region)) +
  geom_col() +
  theme_bw() +
  ggsci::scale_fill_d3() +
  labs(title = "Top 10 Countries With the Most Cases") +
  theme(plot.title = element_text(hjust = .5))#  145个国家有cases,top 10

#有cases的国家汇总
data_havecases = data %>%
  group_by(country_region) %>%
  summarise(n_cases = max(confirmed_cases)) %>% #confirmed_cases = 累计cases
  filter(n_cases != 0)

country = unique(data_havecases$country_region) # 挑出来有cases 的国家

#整理日期数据，准备拿来优化
data = data %>% 
  mutate(date = str_c(date,"20"), 
         date = as.Date.character(date,
                                  format = "%m/%d/%Y")) %>%
  filter(country_region %in% country) #这个data 改过日期，剔除了没有cases的国家


#############################################################
# 定义一个函数：先选定一个国家，提取数据，然后把日期转换为天数
date_to_day = function(df,country_name){
  df_country = df %>%
    filter(country_region == country_name) %>% #选出这个地区的数据
    group_by(date) %>% 
    summarise(cases = sum(confirmed_cases)) %>% # 按日期求累积cases的和，得出每天整个国家的累积cases
    arrange(date) #按日期排序
  
  start_day = which(df_country$cases!=0)[1] # 第一次出现感染的日期对应的行数
  start_date = df_country$date[start_day] # 第一次感染的日期
  df_country = df_country[start_day:nrow(df_country),] %>%
    mutate(days_since_spread = c(1:nrow(.))) # 创建logistic curve 里的t
  
  return(list(start_date = start_date,
              df_country = df_country,
              country.name = country_name))  
} # 返回spread date & 从那一天起感染的数据 & 国家名（用df_country来优化）
#############################################################


# example
t = date_to_day(data,"Portugal")
t$start_date
t$df_country
t$country.name

# 打印10个国家的数据
#for (region in country[1:10]) {
#  res = date_to_day(data,region)
#  print(res$df_country)
#}

t

plot(t$df_country$days_since_spread,t$df_country$cases)

```

# 定义优化用到的函数

```{r}
#先变个型 a <= k, bc <= a, b <= r
#先估计k,三点法不行就用拐点法
k.estimate = function(df){ # para = c(k,a,r)
  cases = df$cases
  n1 = cases[1]
  n2 = median(cases) #2 * t2 = t3?
  n3 = cases[length(cases)]
  if(((2*n1*n2*n3)-n2^2*(n1+n3))/(n1*n3-n2^2) > 0){
    return(((2*n1*n2*n3)-n2^2*(n1+n3))/(n1*n3-n2^2))
  }else
    {
    vec = NULL
    for (i in 2:length(cases)) {
      vec[i-1] = cases[i] - cases[i-1]
    }
    return(2*max(vec))
  }
}

#根据估计的k所得出真实Y
y.real = function(df){
  k = k.estimate(df)
  N = df$cases
  if (k == N) {
    k = k + 0.5
  }
  trans = (k - N)/N
  y.real = NULL
  
  for (each in trans) {
    if (each > 0){
      each = log(each)
      y.real = append(y.real,each)
    }else{
      each = 1/2 * log(each^2)
      y.real = append(y.real,each)
    }
  }
  return(y.real)
}

#拟合值Y-hat
y.hat = function(df,para){ # c(a,r)
  a = para[1]
  r = para[2]
  t = df$days_since_spread
  return(a - r*t)
}


# loss function
loss = function(y.real,y.hat,para){
  return((1/length(y.real)) * sum((y.real - y.hat)^2)
}

# 求梯度
gradient = function(para,y.real,y.hat){ #para = c(a,r)
  grad_a = (-2/length(y.real)) * sum(y.real - y.hat)
  grad_r = (-2/length(y.real)) * sum((y.real - y.hat)*-c(1:length(y.real))) # 此处可能会有错
  return(c(grad_a,grad_r)) # 返回grad
}


## update parameters
para_update = function(para,grad,step){
  para_updated = para - step * grad 
}

```


# 优化过程

```{r}
optimizer = function(para, df, tol = 1e-10, maxiter = 20000){
  k = k.estimate(df)
  y.real = y.real(df)
  y.hat = y.hat(df,para)
  
  loss_prev = -Inf
  loss_cur = loss(y.real,y.hat,para) # loss
  para_cur = para
  iter = 1
  res = data.frame(a = para_cur[1], r = para_cur[2], loss = loss_cur,iter = iter)
  
  while (abs(loss_cur - loss_prev) > tol && iter < maxiter) {
    iter = iter + 1
    print(iter)
    step = 1
    #print(para_cur)
    loss_prev = loss_cur
    para_prev = para_cur
    
    grad = gradient(para_prev, y.real = y.real, y.hat = y.hat)
    
    #print(grad)
    
    para_cur = para_prev - step * grad # update parameters

    #print(para_cur)
    
    y.hat = y.hat(df,para_cur) #更新参数后的y.hat
    #print(y.hat)
    
    loss_cur = loss(y.real = y.real, y.hat = y.hat,para_cur)#更新参数后的loss
    
    #print(paste("loss_cur > loss_pre:", loss_cur > loss_prev))
    print(loss_cur)
    while (loss_cur > loss_prev) {
      step = 0.5 * step
      para_cur = para_prev - step * grad
      y.hat = y.hat(df,para_cur)
      loss_cur = loss(y.real = y.real, y.hat = y.hat,para_cur)
    }
    
    res_tmp  = data.frame(a = para_cur[1], r = para_cur[2], loss = loss_cur,iter = iter)
    res = rbind(res,res_tmp)
    
  }
  res = res %>% mutate(k = k,b = r,c = a/r) %>% select(loss,k,b,c,iter) %>% rename("a" = "k")
  return(res)
}
```


# test 

```{r}
country
t = date_to_day(data,"Nepal")
df = t$df_country
para = c(1,4) # a,r
test = optimizer(para,df) #测试更新所得到参数
test_para = test[nrow(test),c(2:4)] %>% as.numeric()

#创建一个logistic curve
log.curve = function(para,t){
  a = para[1]
  b = para[2]
  c = para[3]
  return(a/(1+exp(-b*(t - c))))
}

pred = log.curve(test_para, t = 1:60)

plot(df$cases)
plot(pred)
```


